description="SSH 연결을 통해 원격 서버의 파일 목록을 조회"
prompt = """
---
allowed-tools: [mcp__ssh-mcp__ssh_list_files, Read]
description: "SSH 연결을 통해 원격 서버의 파일 목록을 조회"
---

# /ssh:list-files - SSH List Files

## Purpose
SSH 연결을 통해 원격 서버의 디렉토리 파일 목록을 조회합니다.

## Usage
```
/ssh:list-files [connectionId] [path]
```

## Arguments
- `connectionId` (필수) - 사용할 연결 ID
- `path` (선택, 기본값: ".") - 조회할 디렉토리 경로

## Execution
1. 연결 ID 유효성 검증 및 상태 확인
2. 지정된 경로의 파일 시스템 탐색
3. 파일 및 디렉토리 정보 수집
4. 권한, 크기, 수정일 등 메타데이터 포함
5. 구조화된 파일 목록 반환

## Claude Code Integration
- Uses mcp__ssh-mcp__ssh_list_files for remote file enumeration
- Leverages Read for file metadata processing
- Maintains secure file system access
- Provides comprehensive file listing with details

## 예시
```json
{
  "connectionId": "conn_123456",
  "path": "/home/ubuntu"
}
```

## 반환값
디렉토리 파일 목록과 상세 정보를 반환합니다.
"""
